### PR TITLE
Technologies section

### PR DESCRIPTION
**Pull request by WarningImHack3r**
Implement the Technologies section according to the Figma file.

## Features
- Elegantly describes the 3 main technologies we (are planning to) use: Svelte(Kit), PostgreSQL & Vercel
- Auto-scrolling tiles detailing the 3 technologies
- Right part with circled images shaped in a triangle, each one with a stunning hover effect
- Paused on hover on a text block

## TODO
- [x] Fix the layout to get the same height for both parts while being uneven columns
- [x] Make responsive
- [x] Add programmatic hover effect trigger for images (a workaround because it's not technically possible), following which tile of the left part is currently displayed

### CODE REVIEW

**Comment by MinixBF** [comment]
After testing it, I don't think the scroll bar looks too good on a PC.
What do you think of the fact that you can click on the technology to change?
I think it's a shame that the counter isn't reset to zero when you arrive at an element. Or even if you scroll down to see one. The scrolling goes backwards, do you think we could fix that?

**Comment by WarningImHack3r** [comment]
> Check the responsive mode, it's broken

Indeed! Did not try with a width this small :O

> After testing it, I don't think the scroll bar looks too good on a PC.

Didn't try it on Windows, I'll find a way to do it

> What do you think of the fact that you can click on the technology to change?

Yes, I love this!!! Easy to do, I will do it

> I think it's a shame that the counter isn't reset to zero when you arrive at an element. Or even if you scroll down to see one. 

I don't really get what you mean...

> The scrolling goes backwards, do you think we could fix that?

It's a deliberate choice, an "infinite carousel" illusion is tricky to make and it looked good enough like this. But if you want I can do it, what do you prefer?

**Comment by MinixBF** [comment]
> It's a deliberate choice, an "infinite carousel" illusion is tricky to make and it looked good enough like this. But if you want I can do it, what do you prefer?

I want the "infinite carousel" but when I'm reading for example. If I scroll to view the PostgreSQL section I don't want to go back to Svelte automatically but to the next one. And after this one back to the first one

**Comment by WarningImHack3r** [comment]
Everything is fixed and improved (c.f. last commit details message), just tell me if you want an infinite scroll effect; otherwise, we should be good to go!

**Review by MinixBF — CHANGES_REQUESTED** [review]
I have found some bugs.
When i hover on technologies, it's create more scroll effect 
https://github.com/EmeraldHQ/Website/assets/40363781/1c27d472-25c7-4d0e-a8a1-3ab937c8bc39

**Comment by MinixBF** [comment]
https://github.com/EmeraldHQ/Website/assets/40363781/40cc7734-301f-48ff-b194-d87d8e953c28

**Review by MinixBF — APPROVED** [review]
Well done! Easier to understand code. 
We can add the glass background located in #97 before merging.

**Pull request merged**
