### PR TITLE
Phone contact in Contact page

### PR DESCRIPTION
**Pull request by WarningImHack3r**
Add the option to contact the sales manager on the Contact page. Consequently, add the `variable` font in the Tailwind config.

> **Note**
> The phone number is clickable. Maybe add something to indicate it? I didn't have any idea.

### CODE REVIEW

**Review by MinixBF — APPROVED** [review]
Nice job

**Comment by MinixBF** [comment]
> The phone number is clickable. Maybe add something to indicate it? I didn't have any idea.
We can add the indication "Click on phone to contact us"

**Comment by WarningImHack3r** [comment]
> We can add the indication "Click on phone to contact us"

Huh I really don't like that... "affordance" ;)

**Comment by WarningImHack3r** [comment]
Ok, @MinixBF what do you think about this? _(Sorry for the ugly GIF)_
Underline version

Also, what do you think about the width/position of the zone? Is it fine in your opinion?

**Comment by MinixBF** [comment]
> Ok, @MinixBF what do you think about this? _(Sorry for the ugly GIF)_
> Underline version
> 
> Also, what do you think about the width/position of the zone? Is it fine in your opinion?

I don't like the underlining on the phone. And hover effect too. What do you think if we put the same effect as you did on the nav bar with the progressive underlining? 

Did you try putting it in the center?

**Comment by WarningImHack3r** [comment]
> I don't like the underlining on the phone. And hover effect too. What do you think if we put the same effect as you did on the nav bar with the progressive underlining? 

Yeah that could be nice, however we "lose" the affordance, but I'm okay with that

> Did you try putting it in the center?

Nope, try it and tell me if I should make the change!

**Comment by MinixBF** [comment]
After asking several people and testing, the conclusion is that we're keeping what you've done. 🎉

**Comment by WarningImHack3r** [comment]
New hover version:
New effect

**Pull request merged**
