### PR TITLE
Navigation & links

### PR DESCRIPTION
**Pull request by WarningImHack3r**
Changes we talked about in [my comment](https://github.com/EmeraldHQ/Website/pull/97#issuecomment-1702748328) in #97.

### Navigation bar
- Add missing links in the navigation bar
- Remove `contact` from the `navbarItems` as it does not belong here and is never used in the markup anyway
- Navigation bar items:
	- Use `goto` if the link starts with `/` (should cover 100% of the cases), else keep `scrollTo`
	- Add support for "active" links that can't be clicked onto, to replace usual links with static underlined labels if they point to the current displayed page. They should be future-proof and work out of the box.

### Footer
- Remove the Legal part (not needed)
- Make links clickable only if their target is not `.`
	- Change "default target" to `.` instead of `/` (because we have a link to Home)
- Rework logic to improve responsiveness, get rid of `tailwindXlScreen` in JS, and reduce the usage of `tailwindXsScreen`
- Fix the scroll-to-top button getting overlapped by `Emerald Studio` on some specific screen sizes (regression from #18?)

### Other
- Add `type="button"` to all `<button>`s
- Comment out buttons that are not used yet in `/`
- Add comments

### CODE REVIEW

**Comment by MinixBF** [comment]
Points to discuss :
We need to add dropdowns in the navbar to navigate. (solutions, company)

>Legal

No need, we can remove it 

>Footer links
What do we do with the footer items links for now? All of them will be linked to pages that don't yet exist, so we can't do much about them for now. My idea: keep them as-is but make them non-clickable if their href is /. As no footer link will ever link to /, I think it can do the trick. However, we will likely have to remove this condition entirely once all the links are made.

Make them non-clickable and after going to the next step, write the blog section with markdown files. Let's move to another PR
For the pages in the "Solutions" section and  others "See more" button

> "See more" buttons
In that same idea of not leaving any clickable element "not done", we will have to comment/remove temporarily all buttons in the pages that are not bound yet to a future page. Do we also do that in this PR?

I have comment button see more #97

**Comment by WarningImHack3r** [comment]
> We need to add dropdowns in the navbar to navigate. (solutions, company)

Yes, we do! But I feel like it's not something we have to do _right now_, it's fine enough to wait and make it the "navbar 2.0"

> No need, we can remove it

On its way

> Make them non-clickable

On its way too

> I have comment button see more #97

Ok but:
- What about the other "See more" buttons all across the page? Do we comment them (in this PR)? Remove them?
- Depending on your answer, do we "move" your comment in #97 in this PR instead so we do all of them in the same place?

**Comment by WarningImHack3r** [comment]
Updated PR's description after changes + discussion

**Comment by MinixBF** [comment]
I think we can only comment here, just because the next step is to uncomment and add the page link to them.

**Comment by WarningImHack3r** [comment]
Ok so let's keep your commenting on #97, and we will comment the rest of those buttons in this PR (if that's what you mean)!

**Review by MinixBF — APPROVED** [review]

**Pull request merged**
