### PR TITLE
Contact page

### PR DESCRIPTION
**Pull request by WarningImHack3r**
Make the contact page.

## Related changes
- Add links to `/contact` everywhere
- Add spinner SVG (to change later for a library one?)

## Additional changes
- Change `Button` `type` prop to `styleType` to avoid confusion
- Change `Button`'s default type to `button` instead of the default `submit`
	- Add a boolean prop to use `submit` instead of `button` that is disabled by default
- Rename border class usages from `border-[1px]` to `border` (which is exactly the same but not hardcoded)
- Change the OpenGraph banner size on the home page to match the new one after #18

### CODE REVIEW

**Review by MinixBF — CHANGES_REQUESTED** [review]
Can we change the background color of the Budget options? To make it more accessible. 
For the spinner, yes, we can.

**Comment by WarningImHack3r** [comment]
> Can we change the background color of the Budget options? To make it more accessible.

I don't know what you mean by inaccessible background but I indeed forgot to add the dropdown arrow I removed 😅 pushing at 3 AM can make you forget stuff!

> For the spinner, yes, we can.

What do "we can"? Change it to a spinner we find in a library? Yes of course, but the ones we use right now don't contain any unfortunately, and I'm not really willing to add a lib only for that icon...
Also, as it's for a thing we barely see 1s when we press a button, it's not really a big deal and in my opinion, we can solve that issue later, can't we?

**Review by MinixBF — CHANGES_REQUESTED** [review]
When selecting a budget, this background.
image

The placeholder "Choisissez un budget" is white, making like others gray

**Comment by WarningImHack3r** [comment]
> When selecting a budget, this background.

Oh okay, I didn't get what you mean because it's once again a Windows issue. Dropdowns like this are not stylable with CSS AFAIK and are OS-dependent. I can [try to change the color/bg color](https://stackoverflow.com/a/7208825/12070367), but Windows should NOT choose to only get the text color and font without changing the background 😅 what an OS...

**Comment by WarningImHack3r** [comment]
> The placeholder "Choisissez un budget" is white, making like others gray

Can you please try on your (Windows) side to set a black background on all (one) `<option>`?

**Comment by WarningImHack3r** [comment]
Thanks @MinixBF for 72f54c0, any screenshot to see the before/after? ^^

**Review by MinixBF — APPROVED** [review]

**Pull request merged**
